// apps/admin-frontend/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import type { Actor } from '@domk/shared-types';
import { api, ApiRequestError } from './api';

const actor = ref<Actor | null>(null);
const error = ref<string | null>(null);

const THEME_STORAGE_KEY = 'admin-theme';
type ThemePref = 'light' | 'dark';

function systemThemePref(): ThemePref {
  return window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
}

function applyTheme(next: ThemePref): void {
  document.documentElement.setAttribute('data-theme', next);
}

const theme = ref<ThemePref>(
  (localStorage.getItem(THEME_STORAGE_KEY) as ThemePref | null) ?? systemThemePref(),
);
applyTheme(theme.value);

function toggleTheme(): void {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
  localStorage.setItem(THEME_STORAGE_KEY, theme.value);
  applyTheme(theme.value);
}

/**
 * `whoami` doubles as the app's readiness check: it proves Access let us
 * through *and* that this identity is in the admins table, which are two
 * different failures worth telling apart on screen.
 */
onMounted(async () => {
  try {
    actor.value = (await api.whoami()).actor;
  } catch (err) {
    error.value =
      err instanceof ApiRequestError
        ? `${err.message} (${err.code})`
        : 'Could not reach the admin API';
  }
});

const isOwner = () => actor.value?.type === 'service' || actor.value?.role === 'owner';
</script>

<template>
  <div class="layout">
    <header class="topbar">
      <span class="brand">CF Shortlinks</span>
      <nav class="tabs">
        <RouterLink to="/links">Links</RouterLink>
        <RouterLink to="/stats">Stats</RouterLink>
        <RouterLink v-if="isOwner()" to="/tokens">Service tokens</RouterLink>
        <RouterLink v-if="isOwner()" to="/admins">Admins</RouterLink>
        <RouterLink v-if="isOwner()" to="/themes">Themes</RouterLink>
      </nav>
      <button
        type="button"
        class="theme-toggle"
        :aria-label="theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'"
        @click="toggleTheme"
      >{{ theme === 'dark' ? '☀' : '🌙' }}</button>
      <span v-if="actor" class="identity">
        {{ actor.type === 'human' ? `${actor.email} · ${actor.role}` : `service · ${actor.name}` }}
        <a href="/cdn-cgi/access/logout" class="logout">Log out</a>
      </span>
    </header>

    <div v-if="error" class="banner error">{{ error }}</div>
    <RouterView v-else-if="actor" />
    <p v-else class="empty">Loading…</p>
  </div>
</template>

// apps/admin-frontend/src/App.tsx
import { Outlet, useLocation, useNavigate } from 'react-router-dom';
import { Banner, Button, Link, Loader, Tabs, Text, Toasty } from '@cloudflare/kumo';
import { Moon, Sun, WarningCircle } from '@phosphor-icons/react';
import { WhoamiProvider, useWhoami, useIsOwner } from './lib/whoami';
import { ThemeProvider, useTheme } from './lib/theme';
import { appToastManager } from './lib/toast';

function TopBar() {
  const navigate = useNavigate();
  const location = useLocation();
  const { actor } = useWhoami();
  const isOwner = useIsOwner();
  const { theme, toggle } = useTheme();
  const identity = actor
    ? actor.type === 'human'
      ? `${actor.email} · ${actor.role}`
      : `service · ${actor.name}`
    : null;

  const tabs = [
    { value: 'links', label: 'Links' },
    { value: 'stats', label: 'Stats' },
    ...(isOwner
      ? [
          { value: 'tokens', label: 'Service tokens' },
          { value: 'admins', label: 'Admins' },
          { value: 'themes', label: 'Themes' },
        ]
      : []),
  ];
  const active = location.pathname.split('/')[1] || 'links';

  return (
    <header className="sticky top-0 z-10 border-b border-kumo-line bg-kumo-base">
      <div className="mx-auto flex max-w-[1200px] flex-wrap items-center gap-x-6 gap-y-3 px-5 py-3">
        <span className="shrink-0">
          <Text variant="heading">CF Shortlinks</Text>
        </span>
        <nav className="min-w-0 flex-1 overflow-x-auto">
          <Tabs
            variant="underline"
            tabs={tabs}
            value={tabs.some((t) => t.value === active) ? active : 'links'}
            onValueChange={(v) => navigate(`/${v}`)}
          />
        </nav>
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            shape="square"
            icon={theme === 'dark' ? <Sun /> : <Moon />}
            aria-label={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'}
            onClick={toggle}
          />
          {identity ? (
            <span className="text-sm text-kumo-subtle">
              {identity}{' '}
              <Link href="/cdn-cgi/access/logout" variant="inline">
                Log out
              </Link>
            </span>
          ) : null}
        </div>
      </div>
    </header>
  );
}

function Shell() {
  const { error, loading } = useWhoami();

  return (
    <>
      <TopBar />
      <main className="page">
        {error ? (
          <Banner
            variant="error"
            icon={<WarningCircle weight="fill" />}
            title="Admin API unavailable"
            description={error}
          />
        ) : loading ? (
          <div className="flex justify-center py-16">
            <Loader />
          </div>
        ) : (
          <Outlet />
        )}
      </main>
    </>
  );
}

export function App() {
  return (
    <ThemeProvider>
      <Toasty toastManager={appToastManager}>
        <WhoamiProvider>
          <Shell />
        </WhoamiProvider>
      </Toasty>
    </ThemeProvider>
  );
}
