// apps/admin-frontend/src/views/AdminsView.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { api, ApiRequestError, type AdminRecord } from '../api';

const admins = ref<AdminRecord[]>([]);
const error = ref<string | null>(null);
const form = reactive({ email: '', role: 'editor' as 'owner' | 'editor' });

async function load(): Promise<void> {
  error.value = null;
  try {
    admins.value = (await api.listAdmins()).items;
  } catch (err) {
    error.value = err instanceof ApiRequestError ? err.message : String(err);
  }
}

onMounted(load);

async function run(action: () => Promise<unknown>): Promise<void> {
  error.value = null;
  try {
    await action();
    await load();
  } catch (err) {
    error.value = err instanceof ApiRequestError ? err.message : String(err);
  }
}

const add = () =>
  run(async () => {
    await api.createAdmin(form.email.trim(), form.role);
    form.email = '';
    form.role = 'editor';
  });

const remove = (admin: AdminRecord) =>
  confirm(`Remove ${admin.email}?`) ? run(() => api.deleteAdmin(admin.email)) : Promise.resolve();
</script>

<template>
  <h1>Admins</h1>

  <div class="card">
    <h2>Identity vs authorization</h2>
    <p class="muted" style="margin: 0">
      Cloudflare Access decides who can reach this app at all. This list decides who can use it
      once they're through, and in what role. Adding someone here does nothing unless the Access
      policy also lets them in.
    </p>
  </div>

  <div v-if="error" class="banner error">{{ error }}</div>

  <form class="card" @submit.prevent="add">
    <h2>Add an admin</h2>
    <div class="row">
      <div class="field field--wide">
        <label for="email">Email (as your IdP reports it)</label>
        <input id="email" v-model="form.email" type="email" required placeholder="you@example.com" />
      </div>
      <div class="field">
        <label for="role">Role</label>
        <select id="role" v-model="form.role">
          <option value="editor">editor — manage links</option>
          <option value="owner">owner — also manage admins and tokens</option>
        </select>
      </div>
    </div>
    <button type="submit">Add</button>
  </form>

  <div class="card">
    <p v-if="!admins.length" class="empty">No admins yet.</p>
    <table v-else class="responsive">
      <thead>
        <tr>
          <th>Email</th>
          <th>Role</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="admin in admins" :key="admin.email">
          <td class="mono" data-label="Email">{{ admin.email }}</td>
          <td data-label="Role"><span class="pill">{{ admin.role }}</span></td>
          <td class="cell-actions">
            <button class="link danger" @click="remove(admin)">Remove</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// apps/admin-frontend/src/views/AdminsView.tsx
import { useState } from 'react';
import { Badge, Button, Dialog, Input, Select, Table, Text } from '@cloudflare/kumo';
import { Plus } from '@phosphor-icons/react';
import { api, type AdminRecord } from '../api';
import { errorMessage } from '../lib/errors';
import { useAsyncData } from '../lib/useAsyncData';
import { PageHeader } from '../components/PageHeader';
import { Card } from '../components/Card';
import { ErrorBanner } from '../components/ErrorBanner';
import { ConfirmButton } from '../components/ConfirmButton';
import { toast } from '../lib/toast';

export function AdminsView() {
  const admins = useAsyncData(() => api.listAdmins().then((r) => r.items), []);

  const [open, setOpen] = useState(false);
  const [email, setEmail] = useState('');
  const [role, setRole] = useState<'owner' | 'editor'>('editor');
  const [formError, setFormError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  async function add(e: React.FormEvent) {
    e.preventDefault();
    setBusy(true);
    setFormError(null);
    try {
      await api.createAdmin(email.trim(), role);
      toast('Admin added', 'success');
      setOpen(false);
      setEmail('');
      setRole('editor');
      admins.reload();
    } catch (err) {
      setFormError(errorMessage(err));
    } finally {
      setBusy(false);
    }
  }

  async function remove(record: AdminRecord) {
    try {
      await api.deleteAdmin(record.email);
      toast(`Removed ${record.email}`, 'success');
      admins.reload();
    } catch (err) {
      admins.setError(errorMessage(err));
    }
  }

  return (
    <div className="grid gap-6">
      <PageHeader
        title="Admins"
        description="Cloudflare Access decides who can reach this app. This list decides who can use it once they're through, and in what role — adding someone here does nothing unless the Access policy also lets them in."
        actions={
          <Button variant="primary" icon={<Plus />} onClick={() => setOpen(true)}>
            Add admin
          </Button>
        }
      />

      <ErrorBanner message={admins.error} />

      <Card className="!p-0">
        {admins.data && admins.data.length > 0 ? (
          <Table>
            <Table.Header>
              <Table.Row>
                <Table.Head>Email</Table.Head>
                <Table.Head>Role</Table.Head>
                <Table.Head className="text-right">Actions</Table.Head>
              </Table.Row>
            </Table.Header>
            <Table.Body>
              {admins.data.map((record) => (
                <Table.Row key={record.email}>
                  <Table.Cell>
                    <Text variant="mono">{record.email}</Text>
                  </Table.Cell>
                  <Table.Cell>
                    <Badge variant={record.role === 'owner' ? 'primary' : 'neutral'}>
                      {record.role}
                    </Badge>
                  </Table.Cell>
                  <Table.Cell className="text-right">
                    <ConfirmButton
                      label="Remove"
                      confirmLabel="Remove"
                      title={`Remove ${record.email}?`}
                      description="They lose access to this app immediately. Access itself is unaffected."
                      onConfirm={() => remove(record)}
                    />
                  </Table.Cell>
                </Table.Row>
              ))}
            </Table.Body>
          </Table>
        ) : (
          <p className="px-5 py-4 text-sm text-kumo-subtle">No admins yet.</p>
        )}
      </Card>

      <Dialog.Root open={open} onOpenChange={setOpen}>
        <Dialog className="p-6">
          <Dialog.Title className="text-lg font-semibold">Add an admin</Dialog.Title>
          <Dialog.Description className="mt-1 mb-4">
            <Text variant="secondary">Enter the email exactly as your IdP reports it.</Text>
          </Dialog.Description>
          <form className="grid gap-4" onSubmit={add}>
            {formError ? (
              <Text variant="error" size="sm">
                {formError}
              </Text>
            ) : null}
            <Input
              label="Email"
              type="email"
              required
              placeholder="you@example.com"
              value={email}
              onChange={(e) => setEmail(e.currentTarget.value)}
            />
            <Select
              label="Role"
              value={role}
              onValueChange={(v) => setRole((v as 'owner' | 'editor') ?? 'editor')}
              items={{
                editor: 'editor — manage links',
                owner: 'owner — also manage admins and tokens',
              }}
            />
            <div className="mt-2 flex justify-end gap-2">
              <Dialog.Close render={(p) => <Button {...p} variant="secondary">Cancel</Button>} />
              <Button type="submit" variant="primary" loading={busy}>
                Add
              </Button>
            </div>
          </form>
        </Dialog>
      </Dialog.Root>
    </div>
  );
}
