// apps/admin-frontend/src/views/LinksView.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import type { CreateLinkInput, Link, Theme, UpdateLinkInput } from '@domk/shared-types';
import { api, ApiRequestError } from '../api';
import { derivePasswordPayload } from '../pbkdf2';

const links = ref<Link[]>([]);
const themes = ref<Theme[]>([]);
const total = ref(0);
const loading = ref(false);
const error = ref<string | null>(null);
const notice = ref<string | null>(null);
const editingId = ref<number | null>(null);

const PAGE_SIZE = 25;
const offset = ref(0);
const rangeText = () =>
  total.value === 0 ? 'No links' : `${offset.value + 1}–${offset.value + links.value.length} of ${total.value}`;

const filters = reactive({ q: '', active: '' });
const form = reactive({
  slug: '',
  destination: '',
  expiresAt: '',
  tags: '',
  active: true,
  passwordEnabled: false,
  /** In-memory only — never sent as-is, only the PBKDF2-derived payload is. */
  passwordPlaintext: '',
  themeId: null as number | null,
});

const themeName = (themeId: number | null) => themes.value.find((t) => t.id === themeId)?.name ?? '—';

/** Only the parts that actually apply — an unremarkable link shows nothing. */
function secondaryLine(link: Link): string {
  const parts: string[] = [];
  if (link.tags.length) parts.push(link.tags.join(', '));
  if (link.expiresAt) parts.push(`expires ${formatDate(link.expiresAt)}`);
  if (link.themeId !== null) parts.push(`theme: ${themeName(link.themeId)}`);
  return parts.join(' · ');
}

function reportError(err: unknown): void {
  error.value = err instanceof ApiRequestError ? err.message : String(err);
}

async function load(): Promise<void> {
  loading.value = true;
  error.value = null;
  try {
    const page = await api.listLinks({
      q: filters.q,
      active: filters.active,
      limit: String(PAGE_SIZE),
      offset: String(offset.value),
    });
    links.value = page.items;
    total.value = page.total;
  } catch (err) {
    reportError(err);
  } finally {
    loading.value = false;
  }
}

/** A changed search/filter invalidates the current page position. */
function search(): void {
  offset.value = 0;
  void load();
}

function prevPage(): void {
  offset.value = Math.max(0, offset.value - PAGE_SIZE);
  void load();
}

function nextPage(): void {
  offset.value += PAGE_SIZE;
  void load();
}

async function loadThemes(): Promise<void> {
  try {
    themes.value = (await api.listThemes()).items;
  } catch {
    // Non-fatal: the form still works without theme options, just with none to pick.
  }
}

onMounted(() => {
  void load();
  void loadThemes();
});

function resetForm(): void {
  editingId.value = null;
  Object.assign(form, {
    slug: '',
    destination: '',
    expiresAt: '',
    tags: '',
    active: true,
    passwordEnabled: false,
    passwordPlaintext: '',
    themeId: null,
  });
}

function startEdit(link: Link): void {
  editingId.value = link.id;
  Object.assign(form, {
    slug: link.slug,
    destination: link.destination,
    // <input type="datetime-local"> wants a local ISO string with no zone.
    expiresAt: link.expiresAt ? toLocalInput(link.expiresAt) : '',
    tags: link.tags.join(', '),
    active: link.active,
    // The API never returns the password itself (write-only) — only whether
    // one is set. Leaving the password field blank on save keeps it as-is.
    passwordEnabled: link.passwordProtected,
    passwordPlaintext: '',
    themeId: link.themeId,
  });
}

function toLocalInput(epochMs: number): string {
  const d = new Date(epochMs);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

async function submit(): Promise<void> {
  error.value = null;
  notice.value = null;

  const payload: Record<string, unknown> = {
    slug: form.slug.trim() || undefined,
    destination: form.destination.trim(),
    expiresAt: form.expiresAt ? new Date(form.expiresAt).getTime() : null,
    tags: form.tags
      .split(',')
      .map((t) => t.trim())
      .filter(Boolean),
    active: form.active,
    themeId: form.themeId,
  };

  if (form.passwordEnabled) {
    if (form.passwordPlaintext) {
      payload.passwordVerifier = await derivePasswordPayload(form.passwordPlaintext);
    } else if (!editingId.value) {
      error.value = 'Enter a password to protect a new link.';
      return;
    }
    // else: editing, protection stays on, password left unchanged — omit the field entirely.
  } else if (editingId.value) {
    // Explicitly unchecked on an existing link — clear the stored password.
    payload.passwordVerifier = null;
  }

  try {
    const result = editingId.value
      ? await api.updateLink(editingId.value, payload as unknown as UpdateLinkInput)
      : await api.createLink(payload as unknown as CreateLinkInput);
    notice.value = `Saved ${result.shortUrl}`;
    resetForm();
    await load();
  } catch (err) {
    reportError(err);
  }
}

async function remove(link: Link): Promise<void> {
  if (!confirm(`Delete /${link.slug}? The short link stops working immediately.`)) return;
  error.value = null;
  try {
    await api.deleteLink(link.id);
    if (editingId.value === link.id) resetForm();
    await load();
  } catch (err) {
    reportError(err);
  }
}

async function toggleActive(link: Link): Promise<void> {
  error.value = null;
  try {
    await api.updateLink(link.id, { active: !link.active });
    await load();
  } catch (err) {
    reportError(err);
  }
}

async function copy(shortUrl: string): Promise<void> {
  await navigator.clipboard.writeText(shortUrl);
  notice.value = `Copied ${shortUrl}`;
}

const shortUrlFor = (link: Link) => `https://${import.meta.env.VITE_SHORT_DOMAIN}/${link.slug}`;
const formatDate = (epochMs: number) => new Date(epochMs).toLocaleDateString();
</script>

<template>
  <h1>Links</h1>

  <div v-if="error" class="banner error">{{ error }}</div>
  <div v-if="notice" class="banner ok">{{ notice }}</div>

  <form class="card" @submit.prevent="submit">
    <h2>{{ editingId ? 'Edit link' : 'New link' }}</h2>
    <div class="row">
      <div class="field">
        <label for="slug">Slug</label>
        <input id="slug" v-model="form.slug" placeholder="leave blank to generate" />
      </div>
      <div class="field field--wide">
        <label for="destination">Destination</label>
        <input id="destination" v-model="form.destination" required placeholder="https://…" />
      </div>
    </div>
    <div class="row">
      <div class="field">
        <label for="expires">Expires (optional)</label>
        <input id="expires" v-model="form.expiresAt" type="datetime-local" />
      </div>
      <div class="field">
        <label for="tags">Tags (comma separated)</label>
        <input id="tags" v-model="form.tags" placeholder="work, social" />
      </div>
      <div class="field field--narrow">
        <label for="active">Active</label>
        <input id="active" v-model="form.active" type="checkbox" />
      </div>
    </div>
    <div class="row">
      <div class="field" style="max-width: 200px">
        <label for="password-enabled">Password protect this link</label>
        <input
          id="password-enabled"
          v-model="form.passwordEnabled"
          type="checkbox"
        />
      </div>
      <div class="field" v-if="form.passwordEnabled">
        <label for="password">Password{{ editingId ? ' (leave blank to keep current)' : '' }}</label>
        <input id="password" v-model="form.passwordPlaintext" type="password" placeholder="••••••••" />
      </div>
      <div class="field">
        <label for="theme">Theme (for the unlock page)</label>
        <select id="theme" v-model="form.themeId">
          <option :value="null">Default</option>
          <option v-for="theme in themes" :key="theme.id" :value="theme.id">{{ theme.name }}</option>
        </select>
      </div>
    </div>
    <div class="actions">
      <button type="submit">{{ editingId ? 'Save changes' : 'Create link' }}</button>
      <button v-if="editingId" type="button" class="secondary" @click="resetForm">Cancel</button>
    </div>
  </form>

  <div class="card">
    <div class="row" style="margin-bottom: 12px">
      <input v-model="filters.q" placeholder="Search slug or destination" @keyup.enter="search" />
      <select v-model="filters.active" @change="search">
        <option value="">All</option>
        <option value="true">Active only</option>
        <option value="false">Inactive only</option>
      </select>
      <button class="secondary" style="max-width: 120px" @click="search">Search</button>
    </div>

    <p v-if="loading" class="empty">Loading…</p>
    <p v-else-if="!links.length" class="empty">No links yet.</p>
    <table v-else class="responsive">
      <thead>
        <tr>
          <th>Slug</th>
          <th>Destination</th>
          <th>State</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="link in links" :key="link.id">
          <td class="mono" data-label="Slug">/{{ link.slug }}</td>
          <td data-label="Destination" class="cell-full">
            <a class="truncate mono" :href="link.destination" target="_blank" rel="noopener noreferrer">
              {{ link.destination }}
            </a>
            <div v-if="secondaryLine(link)" class="muted" style="font-size: 12px; margin-top: 2px">
              {{ secondaryLine(link) }}
            </div>
          </td>
          <td data-label="State">
            <span class="pill" :class="link.active ? 'on' : 'off'">
              {{ link.active ? 'active' : 'off' }}
            </span>
            <span v-if="link.passwordProtected" class="pill accent" style="margin-left: 4px">protected</span>
          </td>
          <td class="cell-menu">
            <details class="menu">
              <summary>⋮</summary>
              <div class="menu-items">
                <button type="button" @click="copy(shortUrlFor(link))">Copy short URL</button>
                <button type="button" @click="startEdit(link)">Edit</button>
                <button type="button" @click="toggleActive(link)">
                  {{ link.active ? 'Disable' : 'Enable' }}
                </button>
                <RouterLink :to="`/links/${link.slug}/stats`">Stats</RouterLink>
                <button type="button" class="danger" @click="remove(link)">Delete</button>
              </div>
            </details>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="pagination">
      <p class="muted" style="margin: 0">{{ rangeText() }}</p>
      <div class="actions">
        <button class="secondary" :disabled="offset === 0" @click="prevPage">Prev</button>
        <button class="secondary" :disabled="offset + links.length >= total" @click="nextPage">Next</button>
      </div>
    </div>
  </div>
</template>

// apps/admin-frontend/src/views/LinksView.tsx
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Badge,
  Button,
  Checkbox,
  Dialog,
  DropdownMenu,
  Input,
  Loader,
  Select,
  Table,
  Text,
} from '@cloudflare/kumo';
import {
  Copy,
  DotsThreeVertical,
  PencilSimple,
  Plus,
  Prohibit,
  TrashSimple,
  ChartBar,
  CheckCircle,
} from '@phosphor-icons/react';
import type { CreateLinkInput, Link, Theme, UpdateLinkInput } from '@domk/shared-types';
import { api } from '../api';
import { derivePasswordPayload } from '../pbkdf2';
import { errorMessage } from '../lib/errors';
import { useAsyncData } from '../lib/useAsyncData';
import { formatDate, toLocalInput } from '../lib/format';
import { PageHeader } from '../components/PageHeader';
import { Card } from '../components/Card';
import { ErrorBanner } from '../components/ErrorBanner';
import { toast } from '../lib/toast';

const PAGE_SIZE = 25;
const SHORT_DOMAIN = import.meta.env.VITE_SHORT_DOMAIN;

const BLANK_FORM = {
  slug: '',
  destination: '',
  expiresAt: '',
  tags: '',
  active: true,
  passwordEnabled: false,
  passwordPlaintext: '',
  themeId: null as number | null,
};
type FormState = typeof BLANK_FORM;

const shortUrlFor = (slug: string) => `https://${SHORT_DOMAIN}/${slug}`;

export function LinksView() {
  const navigate = useNavigate();

  const [q, setQ] = useState('');
  const [queryInput, setQueryInput] = useState('');
  const [activeFilter, setActiveFilter] = useState<'' | 'true' | 'false'>('');
  const [offset, setOffset] = useState(0);

  const page = useAsyncData(
    () =>
      api.listLinks({
        q,
        active: activeFilter,
        limit: String(PAGE_SIZE),
        offset: String(offset),
      }),
    [q, activeFilter, offset],
  );
  const themes = useAsyncData(() => api.listThemes().then((r) => r.items), []);
  const themeList: Theme[] = themes.data ?? [];

  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState<FormState>(BLANK_FORM);
  const [formError, setFormError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<Link | null>(null);

  const links = page.data?.items ?? [];
  const total = page.data?.total ?? 0;
  const rangeText = useMemo(
    () =>
      total === 0
        ? 'No links'
        : `${offset + 1}–${offset + links.length} of ${total}`,
    [offset, links.length, total],
  );

  const themeItems = useMemo(() => {
    const map: Record<string, string> = { '': 'Default' };
    for (const t of themeList) map[String(t.id)] = t.name;
    return map;
  }, [themeList]);

  function runSearch() {
    setOffset(0);
    setQ(queryInput);
  }

  function openCreate() {
    setEditingId(null);
    setForm(BLANK_FORM);
    setFormError(null);
    setDialogOpen(true);
  }

  function openEdit(link: Link) {
    setEditingId(link.id);
    setForm({
      slug: link.slug,
      destination: link.destination,
      expiresAt: link.expiresAt ? toLocalInput(link.expiresAt) : '',
      tags: link.tags.join(', '),
      active: link.active,
      passwordEnabled: link.passwordProtected,
      passwordPlaintext: '',
      themeId: link.themeId,
    });
    setFormError(null);
    setDialogOpen(true);
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setFormError(null);

    const payload: Record<string, unknown> = {
      slug: form.slug.trim() || undefined,
      destination: form.destination.trim(),
      expiresAt: form.expiresAt ? new Date(form.expiresAt).getTime() : null,
      tags: form.tags
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean),
      active: form.active,
      themeId: form.themeId,
    };

    if (form.passwordEnabled) {
      if (form.passwordPlaintext) {
        payload.passwordVerifier = await derivePasswordPayload(form.passwordPlaintext);
      } else if (!editingId) {
        setFormError('Enter a password to protect a new link.');
        return;
      }
      // editing + blank password → leave the stored password untouched (omit the field).
    } else if (editingId) {
      // Explicitly unchecked on an existing link — clear the stored password.
      payload.passwordVerifier = null;
    }

    setBusy(true);
    try {
      const result = editingId
        ? await api.updateLink(editingId, payload as unknown as UpdateLinkInput)
        : await api.createLink(payload as unknown as CreateLinkInput);
      toast(`Saved ${result.shortUrl}`, 'success');
      setDialogOpen(false);
      page.reload();
    } catch (err) {
      setFormError(errorMessage(err));
    } finally {
      setBusy(false);
    }
  }

  async function toggleActive(link: Link) {
    try {
      await api.updateLink(link.id, { active: !link.active });
      page.reload();
    } catch (err) {
      page.setError(errorMessage(err));
    }
  }

  async function confirmDelete() {
    if (!deleteTarget) return;
    setBusy(true);
    try {
      await api.deleteLink(deleteTarget.id);
      toast(`Deleted /${deleteTarget.slug}`, 'success');
      setDeleteTarget(null);
      page.reload();
    } catch (err) {
      page.setError(errorMessage(err));
    } finally {
      setBusy(false);
    }
  }

  async function copy(slug: string) {
    await navigator.clipboard.writeText(shortUrlFor(slug));
    toast(`Copied ${shortUrlFor(slug)}`, 'success');
  }

  function secondaryLine(link: Link): string {
    const parts: string[] = [];
    if (link.tags.length) parts.push(link.tags.join(', '));
    if (link.expiresAt) parts.push(`expires ${formatDate(link.expiresAt)}`);
    if (link.themeId !== null) {
      parts.push(`theme: ${themeList.find((t) => t.id === link.themeId)?.name ?? '—'}`);
    }
    return parts.join(' · ');
  }

  return (
    <div className="grid gap-6">
      <PageHeader
        title="Links"
        actions={
          <Button variant="primary" icon={<Plus />} onClick={openCreate}>
            New link
          </Button>
        }
      />

      <ErrorBanner message={page.error} />

      <Card>
        <form
          className="flex flex-wrap items-end gap-3"
          onSubmit={(e) => {
            e.preventDefault();
            runSearch();
          }}
        >
          <div className="min-w-56 flex-1">
            <Input
              aria-label="Search"
              placeholder="Search slug or destination"
              value={queryInput}
              onChange={(e) => setQueryInput(e.currentTarget.value)}
            />
          </div>
          <Select
            aria-label="Filter by state"
            value={activeFilter}
            onValueChange={(v) => {
              setOffset(0);
              setActiveFilter((v as '' | 'true' | 'false') ?? '');
            }}
            items={{ '': 'All', true: 'Active only', false: 'Inactive only' }}
          />
          <Button type="submit" variant="secondary">
            Search
          </Button>
        </form>
      </Card>

      <Card className="!p-0">
        {page.loading && !page.data ? (
          <div className="flex justify-center py-16">
            <Loader />
          </div>
        ) : links.length === 0 ? (
          <p className="px-5 py-4 text-sm text-kumo-subtle">No links found.</p>
        ) : (
          <Table>
            <Table.Header>
              <Table.Row>
                <Table.Head>Slug</Table.Head>
                <Table.Head>Destination</Table.Head>
                <Table.Head>State</Table.Head>
                <Table.Head className="text-right">Actions</Table.Head>
              </Table.Row>
            </Table.Header>
            <Table.Body>
              {links.map((link) => (
                <Table.Row key={link.id}>
                  <Table.Cell>
                    <Text variant="mono">/{link.slug}</Text>
                  </Table.Cell>
                  <Table.Cell className="max-w-md">
                    <a
                      href={link.destination}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block truncate font-mono text-[0.9em] text-kumo-link hover:underline"
                    >
                      {link.destination}
                    </a>
                    {secondaryLine(link) ? (
                      <Text variant="secondary" size="xs">
                        {secondaryLine(link)}
                      </Text>
                    ) : null}
                  </Table.Cell>
                  <Table.Cell>
                    <span className="flex items-center gap-1.5">
                      <Badge variant={link.active ? 'success' : 'neutral'} appearance="dot">
                        {link.active ? 'active' : 'off'}
                      </Badge>
                      {link.passwordProtected ? <Badge variant="orange">protected</Badge> : null}
                    </span>
                  </Table.Cell>
                  <Table.Cell className="text-right">
                    <DropdownMenu>
                      <DropdownMenu.Trigger
                        render={
                          <Button
                            variant="ghost"
                            shape="square"
                            size="sm"
                            icon={<DotsThreeVertical weight="bold" />}
                            aria-label={`Actions for /${link.slug}`}
                          />
                        }
                      />
                      <DropdownMenu.Content>
                        <DropdownMenu.Item icon={<Copy />} onClick={() => copy(link.slug)}>
                          Copy short URL
                        </DropdownMenu.Item>
                        <DropdownMenu.Item icon={<PencilSimple />} onClick={() => openEdit(link)}>
                          Edit
                        </DropdownMenu.Item>
                        <DropdownMenu.Item
                          icon={link.active ? <Prohibit /> : <CheckCircle />}
                          onClick={() => toggleActive(link)}
                        >
                          {link.active ? 'Disable' : 'Enable'}
                        </DropdownMenu.Item>
                        <DropdownMenu.Item
                          icon={<ChartBar />}
                          onClick={() => navigate(`/links/${link.slug}/stats`)}
                        >
                          Stats
                        </DropdownMenu.Item>
                        <DropdownMenu.Separator />
                        <DropdownMenu.Item
                          icon={<TrashSimple />}
                          variant="danger"
                          onClick={() => setDeleteTarget(link)}
                        >
                          Delete
                        </DropdownMenu.Item>
                      </DropdownMenu.Content>
                    </DropdownMenu>
                  </Table.Cell>
                </Table.Row>
              ))}
            </Table.Body>
          </Table>
        )}
        <div className="flex items-center justify-between gap-4 px-5 py-3">
          <Text variant="secondary" size="sm">
            {rangeText}
          </Text>
          <div className="flex gap-2">
            <Button
              variant="secondary"
              size="sm"
              disabled={offset === 0}
              onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}
            >
              Prev
            </Button>
            <Button
              variant="secondary"
              size="sm"
              disabled={offset + links.length >= total}
              onClick={() => setOffset(offset + PAGE_SIZE)}
            >
              Next
            </Button>
          </div>
        </div>
      </Card>

      {/* Create / edit dialog */}
      <Dialog.Root open={dialogOpen} onOpenChange={setDialogOpen}>
        <Dialog size="lg" className="p-6">
          <Dialog.Title className="text-lg font-semibold">
            {editingId ? 'Edit link' : 'New link'}
          </Dialog.Title>
          <Dialog.Description className="sr-only">
            Configure the short link's destination and options.
          </Dialog.Description>
          <form className="mt-4 grid gap-4" onSubmit={submit}>
            {formError ? (
              <Text variant="error" size="sm">
                {formError}
              </Text>
            ) : null}
            <div className="grid gap-4 sm:grid-cols-[1fr_2fr]">
              <Input
                label="Slug"
                required={false}
                placeholder="auto"
                value={form.slug}
                onChange={(e) => setForm({ ...form, slug: e.currentTarget.value })}
              />
              <Input
                label="Destination"
                required
                placeholder="https://…"
                value={form.destination}
                onChange={(e) => setForm({ ...form, destination: e.currentTarget.value })}
              />
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="grid gap-1.5">
                <label htmlFor="link-expires" className="text-sm text-kumo-default">
                  Expires <span className="text-kumo-subtle">(optional)</span>
                </label>
                <input
                  id="link-expires"
                  type="datetime-local"
                  className="h-9 rounded-md bg-kumo-control px-2 ring ring-kumo-line"
                  value={form.expiresAt}
                  onChange={(e) => setForm({ ...form, expiresAt: e.currentTarget.value })}
                />
              </div>
              <Input
                label="Tags"
                required={false}
                description="Comma separated"
                placeholder="work, social"
                value={form.tags}
                onChange={(e) => setForm({ ...form, tags: e.currentTarget.value })}
              />
            </div>
            <Checkbox
              label="Active"
              checked={form.active}
              onCheckedChange={(checked) => setForm({ ...form, active: Boolean(checked) })}
            />
            <div className="grid gap-3 rounded-lg bg-kumo-recessed p-4">
              <Checkbox
                label="Password protect this link"
                checked={form.passwordEnabled}
                onCheckedChange={(checked) =>
                  setForm({ ...form, passwordEnabled: Boolean(checked) })
                }
              />
              {form.passwordEnabled ? (
                <Input
                  label={
                    editingId ? 'Password (leave blank to keep current)' : 'Password'
                  }
                  type="password"
                  placeholder="••••••••"
                  value={form.passwordPlaintext}
                  onChange={(e) => setForm({ ...form, passwordPlaintext: e.currentTarget.value })}
                />
              ) : null}
              <Select
                label="Unlock-page theme"
                value={form.themeId === null ? '' : String(form.themeId)}
                onValueChange={(v) =>
                  setForm({ ...form, themeId: v ? Number(v) : null })
                }
                items={themeItems}
              />
            </div>
            <div className="mt-2 flex justify-end gap-2">
              <Dialog.Close render={(p) => <Button {...p} variant="secondary">Cancel</Button>} />
              <Button type="submit" variant="primary" loading={busy}>
                {editingId ? 'Save changes' : 'Create link'}
              </Button>
            </div>
          </form>
        </Dialog>
      </Dialog.Root>

      {/* Delete confirmation */}
      <Dialog.Root
        role="alertdialog"
        open={deleteTarget !== null}
        onOpenChange={(o) => !o && setDeleteTarget(null)}
      >
        <Dialog className="p-6">
          <Dialog.Title className="text-lg font-semibold">
            Delete /{deleteTarget?.slug}?
          </Dialog.Title>
          <Dialog.Description className="mt-2">
            <Text variant="secondary">The short link stops working immediately.</Text>
          </Dialog.Description>
          <div className="mt-6 flex justify-end gap-2">
            <Dialog.Close render={(p) => <Button {...p} variant="secondary">Cancel</Button>} />
            <Button variant="destructive" loading={busy} onClick={confirmDelete}>
              Delete
            </Button>
          </div>
        </Dialog>
      </Dialog.Root>
    </div>
  );
}
