// apps/admin-frontend/src/views/LinkStatsView.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import type { LinkStats } from '@domk/shared-types';
import { api, ApiRequestError } from '../api';
import BarChart from '../components/BarChart.vue';
import BreakdownTable from '../components/BreakdownTable.vue';

const props = defineProps<{ slug: string }>();

const stats = ref<LinkStats | null>(null);
const days = ref(7);
const error = ref<string | null>(null);

async function load(): Promise<void> {
  error.value = null;
  try {
    stats.value = await api.linkStats(props.slug, days.value);
  } catch (err) {
    error.value = err instanceof ApiRequestError ? err.message : String(err);
  }
}

onMounted(load);
watch([days, () => props.slug], load);
</script>

<template>
  <h1 class="mono">/{{ slug }}</h1>
  <p><RouterLink to="/links">← All links</RouterLink></p>

  <div v-if="error" class="banner error">{{ error }}</div>

  <div class="card">
    <div class="row" style="align-items: flex-end">
      <div class="field" style="max-width: 200px; margin: 0">
        <label for="days">Window</label>
        <select id="days" v-model.number="days">
          <option :value="1">Last 24 hours</option>
          <option :value="7">Last 7 days</option>
          <option :value="30">Last 30 days</option>
          <option :value="90">Last 90 days</option>
        </select>
      </div>
      <div v-if="stats" style="text-align: right">
        <div class="muted">Clicks</div>
        <div class="stat">{{ stats.totalClicks.toLocaleString() }}</div>
      </div>
    </div>
  </div>

  <template v-if="stats">
    <div class="card">
      <h2>Clicks over time</h2>
      <BarChart :points="stats.series" />
    </div>
    <div class="grid-2">
      <BreakdownTable title="By country" :rows="stats.byCountry" key-label="Country" />
      <BreakdownTable title="By referrer" :rows="stats.byReferrer" key-label="Referrer" />
    </div>
  </template>
</template>

// apps/admin-frontend/src/views/LinkStatsView.tsx
import { useState } from 'react';
import { Link as RouterLink, useParams } from 'react-router-dom';
import { Loader, Text } from '@cloudflare/kumo';
import { ArrowLeft } from '@phosphor-icons/react';
import { api } from '../api';
import { useAsyncData } from '../lib/useAsyncData';
import { PageHeader } from '../components/PageHeader';
import { Card } from '../components/Card';
import { ErrorBanner } from '../components/ErrorBanner';
import { WindowSelector } from '../components/WindowSelector';
import { TimeSeriesChart } from '../components/TimeSeriesChart';
import { BreakdownTable } from '../components/BreakdownTable';

export function LinkStatsView() {
  const { slug = '' } = useParams();
  const [days, setDays] = useState(7);
  const stats = useAsyncData(() => api.linkStats(slug, days), [slug, days]);

  return (
    <div className="grid gap-6">
      <PageHeader
        title={<span className="font-mono">/{slug}</span>}
        description={
          <RouterLink
            to="/links"
            className="inline-flex items-center gap-1 text-kumo-link hover:underline"
          >
            <ArrowLeft /> All links
          </RouterLink>
        }
        actions={<WindowSelector days={days} onChange={setDays} />}
      />

      <ErrorBanner message={stats.error} />

      <Card>
        <div className="flex items-baseline gap-3">
          <Text as="h2" variant="heading">
            {(stats.data?.totalClicks ?? 0).toLocaleString()}
          </Text>
          <Text variant="secondary">clicks in this window</Text>
        </div>
      </Card>

      {stats.loading && !stats.data ? (
        <div className="flex justify-center py-16">
          <Loader />
        </div>
      ) : stats.data ? (
        <>
          <div className="grid gap-2">
            <Text as="h2" variant="heading">
              Clicks over time
            </Text>
            <Card>
              <TimeSeriesChart points={stats.data.series} />
            </Card>
          </div>

          <div className="grid gap-6 md:grid-cols-2">
            <BreakdownTable title="By country" rows={stats.data.byCountry} keyLabel="Country" />
            <BreakdownTable title="By referrer" rows={stats.data.byReferrer} keyLabel="Referrer" />
          </div>
        </>
      ) : null}
    </div>
  );
}
