// apps/admin-frontend/src/views/StatsView.tsx
import { useState } from 'react';
import { Loader, Text } from '@cloudflare/kumo';
import { api } from '../api';
import { useAsyncData } from '../lib/useAsyncData';
import { PageHeader } from '../components/PageHeader';
import { Card } from '../components/Card';
import { ErrorBanner } from '../components/ErrorBanner';
import { WindowSelector } from '../components/WindowSelector';
import { TimeSeriesChart } from '../components/TimeSeriesChart';
import { BreakdownTable } from '../components/BreakdownTable';

export function StatsView() {
  const [days, setDays] = useState(7);
  const stats = useAsyncData(() => api.overview(days), [days]);

  return (
    <div className="grid gap-6">
      <PageHeader
        title="Stats"
        actions={<WindowSelector days={days} onChange={setDays} />}
      />

      <ErrorBanner message={stats.error} />

      <Card>
        <div className="flex items-baseline gap-3">
          <Text as="h2" variant="heading">
            {(stats.data?.totalClicks ?? 0).toLocaleString()}
          </Text>
          <Text variant="secondary">total clicks in this window</Text>
        </div>
      </Card>

      {stats.loading && !stats.data ? (
        <div className="flex justify-center py-16">
          <Loader />
        </div>
      ) : stats.data ? (
        <>
          <div className="grid gap-2">
            <Text as="h2" variant="heading">
              Clicks over time
            </Text>
            <Card>
              <TimeSeriesChart points={stats.data.series} />
            </Card>
          </div>

          <div className="grid gap-6 md:grid-cols-2">
            <BreakdownTable title="Top links" rows={stats.data.topLinks} keyLabel="Slug" />
            <BreakdownTable title="By country" rows={stats.data.byCountry} keyLabel="Country" />
          </div>

          <div className="grid gap-2">
            <BreakdownTable title="Top misses" rows={stats.data.topMisses} keyLabel="Slug" />
            <Text variant="secondary" size="sm">
              Misses are requests for slugs that don't exist — either 404'd or sent to the configured
              fallback. A slug high on this list is one worth creating.
            </Text>
          </div>
        </>
      ) : null}
    </div>
  );
}

// apps/admin-frontend/src/views/StatsView.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import { api, ApiRequestError, type OverviewStats } from '../api';
import BarChart from '../components/BarChart.vue';
import BreakdownTable from '../components/BreakdownTable.vue';

const stats = ref<OverviewStats | null>(null);
const days = ref(7);
const error = ref<string | null>(null);
const loading = ref(false);

async function load(): Promise<void> {
  loading.value = true;
  error.value = null;
  try {
    stats.value = await api.overview(days.value);
  } catch (err) {
    error.value = err instanceof ApiRequestError ? err.message : String(err);
  } finally {
    loading.value = false;
  }
}

onMounted(load);
watch(days, load);
</script>

<template>
  <h1>Stats</h1>

  <div v-if="error" class="banner error">{{ error }}</div>

  <div class="card">
    <div class="row" style="align-items: flex-end">
      <div class="field" style="max-width: 200px; margin: 0">
        <label for="days">Window</label>
        <select id="days" v-model.number="days">
          <option :value="1">Last 24 hours</option>
          <option :value="7">Last 7 days</option>
          <option :value="30">Last 30 days</option>
          <option :value="90">Last 90 days</option>
        </select>
      </div>
      <div v-if="stats" style="text-align: right">
        <div class="muted">Total clicks</div>
        <div class="stat">{{ stats.totalClicks.toLocaleString() }}</div>
      </div>
    </div>
  </div>

  <p v-if="loading" class="empty">Loading…</p>

  <template v-else-if="stats">
    <div class="card">
      <h2>Clicks over time</h2>
      <BarChart :points="stats.series" />
    </div>

    <div class="grid-2">
      <BreakdownTable title="Top links" :rows="stats.topLinks" key-label="Slug" />
      <BreakdownTable title="By country" :rows="stats.byCountry" key-label="Country" />
    </div>

    <BreakdownTable title="Top misses" :rows="stats.topMisses" key-label="Slug" />
    <p class="muted">
      Misses are requests for slugs that don't exist — either 404'd or sent to the
      configured fallback. A slug high on this list is one worth creating.
    </p>
  </template>
</template>
