// apps/admin-frontend/src/components/BreakdownTable.vue
<script setup lang="ts">
import type { StatsBreakdownRow } from '@domk/shared-types';

defineProps<{ title: string; rows: StatsBreakdownRow[]; keyLabel?: string }>();
</script>

<template>
  <div class="card">
    <h2>{{ title }}</h2>
    <p v-if="!rows.length" class="empty">Nothing yet.</p>
    <table v-else>
      <thead>
        <tr>
          <th>{{ keyLabel ?? 'Key' }}</th>
          <th style="text-align: right">Clicks</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="row in rows" :key="row.key">
          <td class="mono"><span class="truncate">{{ row.key }}</span></td>
          <td class="numeric">{{ row.clicks.toLocaleString() }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// apps/admin-frontend/src/components/BreakdownTable.tsx
import { Table, Text } from '@cloudflare/kumo';
import type { StatsBreakdownRow } from '@domk/shared-types';
import { Card } from './Card';

export function BreakdownTable({
  title,
  rows,
  keyLabel = 'Key',
}: {
  title: string;
  rows: StatsBreakdownRow[];
  keyLabel?: string;
}) {
  return (
    <div className="grid gap-2">
      <Text as="h2" variant="heading">
        {title}
      </Text>
      <Card className="!p-0">
        {rows.length === 0 ? (
          <p className="px-5 py-4 text-sm text-kumo-subtle">Nothing yet.</p>
        ) : (
          <Table>
            <Table.Header>
              <Table.Row>
                <Table.Head>{keyLabel}</Table.Head>
                <Table.Head className="text-right">Clicks</Table.Head>
              </Table.Row>
            </Table.Header>
            <Table.Body>
              {rows.map((row) => (
                <Table.Row key={row.key}>
                  <Table.Cell>
                    <Text variant="mono" truncate>
                      {row.key || '—'}
                    </Text>
                  </Table.Cell>
                  <Table.Cell className="text-right tabular-nums">
                    {row.clicks.toLocaleString()}
                  </Table.Cell>
                </Table.Row>
              ))}
            </Table.Body>
          </Table>
        )}
      </Card>
    </div>
  );
}
